spring:
  application:
    name: hql
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:54322/postgres
    username: postgres
    password: postgres

#    jpa:
#      hibernate:
#        ddl-auto: none
#      properties:
#        hibernate:
#          dialect: org.hibernate.dialect.PostgreSQLDialect
#      open-in-view: false


mybatis:
  mapper-locations: classpath:/mapper/*.xml

